      PROGRAM TEST_SPLINE
      INTEGER STATUS, DEGREE, DIM, NCTRLP, TYPE
      PARAMETER (DEGREE=3, DIM=3, NCTRLP=4, TYPE=0)

      DOUBLE PRECISION CTRLP(12), SAMPLES(300)
      INTEGER ACTUAL_SAMPLES

      DATA CTRLP / -0.8D0,-0.8D0,0.0D0, -0.4D0,0.8D0,0.2D0, 0.4D0,-0.8D0,0.6D0, 0.8D0,0.8D0,0.0D0 /

      CALL PS_SPLINE_NEW(DEGREE, DIM, NCTRLP, TYPE, STATUS)
      IF (STATUS .NE. 0) THEN
         PRINT *, 'FAILED TO CREATE SPLINE'
         STOP
      ENDIF

      CALL PS_SPLINE_SET_CTRLP(CTRLP, STATUS)
      IF (STATUS .NE. 0) THEN
         PRINT *, 'FAILED TO SET CONTROL POINTS'
         STOP
      ENDIF

      CALL PS_SPLINE_SAMPLE(100, SAMPLES, ACTUAL_SAMPLES, STATUS)
      IF (STATUS .NE. 0) THEN
         PRINT *, 'FAILED TO SAMPLE SPLINE'
         STOP
      ENDIF

      PRINT *, 'SAMPLED POINTS COUNT:', ACTUAL_SAMPLES
      STOP
      END
